
subdir=common netronome

all:
	#for i in $(subdir); do echo $$i;make -C $(CURDIR)/$i; done;
	make -C $(CURDIR)/common
	make -C $(CURDIR)/netronome

clean:
	#for i in $(subdir); do echo $$i;make -C $(CURDIR)/$i clean; done;
	make -C $(CURDIR)/common clean
	make -C $(CURDIR)/netronome clean